# Generated by Django 2.1.3 on 2018-11-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_loaddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pizzas', to='pizza_app.Address'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pizzas', to='pizza_app.PizzaMenuItem'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pizzas', to='pizza_app.PizzaSize'),
        ),
    ]
